name: Build

on: [ push ]

jobs:
  run-test:
    uses: ./.github/workflows/_test.yml

  build:
    runs-on: ubuntu-latest
    needs: run-test

    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/go-jwt-kc-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-jwt-kc-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/